# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vector.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cvector.proto\x12\tmypackage\"}\n\tSingleton\x12\t\n\x01v\x18\x01 \x03(\x02\x12\x34\n\x08metadata\x18\x02 \x03(\x0b\x32\".mypackage.Singleton.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x12\n\x05\x42\x61tch\x12\t\n\x01\x62\x18\x01 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vector_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SINGLETON_METADATAENTRY._options = None
  _SINGLETON_METADATAENTRY._serialized_options = b'8\001'
  _globals['_SINGLETON']._serialized_start=27
  _globals['_SINGLETON']._serialized_end=152
  _globals['_SINGLETON_METADATAENTRY']._serialized_start=105
  _globals['_SINGLETON_METADATAENTRY']._serialized_end=152
  _globals['_BATCH']._serialized_start=154
  _globals['_BATCH']._serialized_end=172
# @@protoc_insertion_point(module_scope)
