# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vector_new.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10vector_new.proto\x12\rinsert_buffer\"w\n\rMetadataValue\x12\x15\n\x0b\x66loat_value\x18\x01 \x01(\x02H\x00\x12\x13\n\tint_value\x18\x02 \x01(\x03H\x00\x12\x16\n\x0cstring_value\x18\x03 \x01(\tH\x00\x12\x14\n\nbool_value\x18\x04 \x01(\x08H\x00\x42\x0c\n\nvalue_type\"\x96\x01\n\x0cSingletonVec\x12\t\n\x01v\x18\x01 \x03(\x02\x12\x31\n\x03map\x18\x02 \x03(\x0b\x32$.insert_buffer.SingletonVec.MapEntry\x1aH\n\x08MapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.insert_buffer.MetadataValue:\x02\x38\x01\"2\n\x08\x42\x61tchVec\x12&\n\x01s\x18\x01 \x03(\x0b\x32\x1b.insert_buffer.SingletonVec\"\x96\x01\n\x0cSingletonStr\x12\t\n\x01v\x18\x01 \x01(\t\x12\x31\n\x03map\x18\x02 \x03(\x0b\x32$.insert_buffer.SingletonStr.MapEntry\x1aH\n\x08MapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.insert_buffer.MetadataValue:\x02\x38\x01\"2\n\x08\x42\x61tchStr\x12&\n\x01s\x18\x01 \x03(\x0b\x32\x1b.insert_buffer.SingletonStrb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vector_new_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SINGLETONVEC_MAPENTRY._options = None
  _SINGLETONVEC_MAPENTRY._serialized_options = b'8\001'
  _SINGLETONSTR_MAPENTRY._options = None
  _SINGLETONSTR_MAPENTRY._serialized_options = b'8\001'
  _globals['_METADATAVALUE']._serialized_start=35
  _globals['_METADATAVALUE']._serialized_end=154
  _globals['_SINGLETONVEC']._serialized_start=157
  _globals['_SINGLETONVEC']._serialized_end=307
  _globals['_SINGLETONVEC_MAPENTRY']._serialized_start=235
  _globals['_SINGLETONVEC_MAPENTRY']._serialized_end=307
  _globals['_BATCHVEC']._serialized_start=309
  _globals['_BATCHVEC']._serialized_end=359
  _globals['_SINGLETONSTR']._serialized_start=362
  _globals['_SINGLETONSTR']._serialized_end=512
  _globals['_SINGLETONSTR_MAPENTRY']._serialized_start=235
  _globals['_SINGLETONSTR_MAPENTRY']._serialized_end=307
  _globals['_BATCHSTR']._serialized_start=514
  _globals['_BATCHSTR']._serialized_end=564
# @@protoc_insertion_point(module_scope)
